// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination mocks\mock_session.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "auth-cli/internal/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISessionService is a mock of ISessionService interface.
type MockISessionService struct {
	ctrl     *gomock.Controller
	recorder *MockISessionServiceMockRecorder
	isgomock struct{}
}

// MockISessionServiceMockRecorder is the mock recorder for MockISessionService.
type MockISessionServiceMockRecorder struct {
	mock *MockISessionService
}

// NewMockISessionService creates a new mock instance.
func NewMockISessionService(ctrl *gomock.Controller) *MockISessionService {
	mock := &MockISessionService{ctrl: ctrl}
	mock.recorder = &MockISessionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionService) EXPECT() *MockISessionServiceMockRecorder {
	return m.recorder
}

// FinalizeLogin mocks base method.
func (m *MockISessionService) FinalizeLogin(ctx context.Context, userID string) (*dto.SessionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizeLogin", ctx, userID)
	ret0, _ := ret[0].(*dto.SessionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizeLogin indicates an expected call of FinalizeLogin.
func (mr *MockISessionServiceMockRecorder) FinalizeLogin(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizeLogin", reflect.TypeOf((*MockISessionService)(nil).FinalizeLogin), ctx, userID)
}

// Logout mocks base method.
func (m *MockISessionService) Logout(ctx context.Context, rawToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, rawToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockISessionServiceMockRecorder) Logout(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockISessionService)(nil).Logout), ctx, rawToken)
}

// ValidateSession mocks base method.
func (m *MockISessionService) ValidateSession(ctx context.Context, rawToken string) (*dto.AuthenticatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, rawToken)
	ret0, _ := ret[0].(*dto.AuthenticatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockISessionServiceMockRecorder) ValidateSession(ctx, rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockISessionService)(nil).ValidateSession), ctx, rawToken)
}
