// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination mocks\mock_loginsecurity.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockILoginSecurityRepository is a mock of ILoginSecurityRepository interface.
type MockILoginSecurityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILoginSecurityRepositoryMockRecorder
	isgomock struct{}
}

// MockILoginSecurityRepositoryMockRecorder is the mock recorder for MockILoginSecurityRepository.
type MockILoginSecurityRepositoryMockRecorder struct {
	mock *MockILoginSecurityRepository
}

// NewMockILoginSecurityRepository creates a new mock instance.
func NewMockILoginSecurityRepository(ctrl *gomock.Controller) *MockILoginSecurityRepository {
	mock := &MockILoginSecurityRepository{ctrl: ctrl}
	mock.recorder = &MockILoginSecurityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoginSecurityRepository) EXPECT() *MockILoginSecurityRepositoryMockRecorder {
	return m.recorder
}

// IsBlocked mocks base method.
func (m *MockILoginSecurityRepository) IsBlocked(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlocked", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBlocked indicates an expected call of IsBlocked.
func (mr *MockILoginSecurityRepositoryMockRecorder) IsBlocked(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlocked", reflect.TypeOf((*MockILoginSecurityRepository)(nil).IsBlocked), ctx, userID)
}

// RecordFailure mocks base method.
func (m *MockILoginSecurityRepository) RecordFailure(ctx context.Context, userID string, maximumAttempts int, blockDuration time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFailure", ctx, userID, maximumAttempts, blockDuration)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordFailure indicates an expected call of RecordFailure.
func (mr *MockILoginSecurityRepositoryMockRecorder) RecordFailure(ctx, userID, maximumAttempts, blockDuration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFailure", reflect.TypeOf((*MockILoginSecurityRepository)(nil).RecordFailure), ctx, userID, maximumAttempts, blockDuration)
}

// Reset mocks base method.
func (m *MockILoginSecurityRepository) Reset(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockILoginSecurityRepositoryMockRecorder) Reset(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockILoginSecurityRepository)(nil).Reset), ctx, userID)
}
