// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination mocks\mock_auth.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "auth-cli/internal/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAuthService is a mock of IAuthService interface.
type MockIAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthServiceMockRecorder
	isgomock struct{}
}

// MockIAuthServiceMockRecorder is the mock recorder for MockIAuthService.
type MockIAuthServiceMockRecorder struct {
	mock *MockIAuthService
}

// NewMockIAuthService creates a new mock instance.
func NewMockIAuthService(ctrl *gomock.Controller) *MockIAuthService {
	mock := &MockIAuthService{ctrl: ctrl}
	mock.recorder = &MockIAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthService) EXPECT() *MockIAuthServiceMockRecorder {
	return m.recorder
}

// CancelTOTPLogin mocks base method.
func (m *MockIAuthService) CancelTOTPLogin(challengeID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelTOTPLogin", challengeID)
}

// CancelTOTPLogin indicates an expected call of CancelTOTPLogin.
func (mr *MockIAuthServiceMockRecorder) CancelTOTPLogin(challengeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTOTPLogin", reflect.TypeOf((*MockIAuthService)(nil).CancelTOTPLogin), challengeID)
}

// ClearTOTPLoginChallenges mocks base method.
func (m *MockIAuthService) ClearTOTPLoginChallenges() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearTOTPLoginChallenges")
}

// ClearTOTPLoginChallenges indicates an expected call of ClearTOTPLoginChallenges.
func (mr *MockIAuthServiceMockRecorder) ClearTOTPLoginChallenges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearTOTPLoginChallenges", reflect.TypeOf((*MockIAuthService)(nil).ClearTOTPLoginChallenges))
}

// CompleteTOTPLogin mocks base method.
func (m *MockIAuthService) CompleteTOTPLogin(ctx context.Context, challengeID, code string) (*dto.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTOTPLogin", ctx, challengeID, code)
	ret0, _ := ret[0].(*dto.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteTOTPLogin indicates an expected call of CompleteTOTPLogin.
func (mr *MockIAuthServiceMockRecorder) CompleteTOTPLogin(ctx, challengeID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTOTPLogin", reflect.TypeOf((*MockIAuthService)(nil).CompleteTOTPLogin), ctx, challengeID, code)
}

// LoginWithPassword mocks base method.
func (m *MockIAuthService) LoginWithPassword(ctx context.Context, input dto.LoginInput) (*dto.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginWithPassword", ctx, input)
	ret0, _ := ret[0].(*dto.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginWithPassword indicates an expected call of LoginWithPassword.
func (mr *MockIAuthServiceMockRecorder) LoginWithPassword(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginWithPassword", reflect.TypeOf((*MockIAuthService)(nil).LoginWithPassword), ctx, input)
}

// Register mocks base method.
func (m *MockIAuthService) Register(ctx context.Context, input dto.RegisterInput) (*dto.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, input)
	ret0, _ := ret[0].(*dto.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockIAuthServiceMockRecorder) Register(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockIAuthService)(nil).Register), ctx, input)
}
