// Code generated by MockGen. DO NOT EDIT.
// Source: password.go
//
// Generated by this command:
//
//	mockgen -source password.go -destination mocks\mock_password.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPasswordManager is a mock of IPasswordManager interface.
type MockIPasswordManager struct {
	ctrl     *gomock.Controller
	recorder *MockIPasswordManagerMockRecorder
	isgomock struct{}
}

// MockIPasswordManagerMockRecorder is the mock recorder for MockIPasswordManager.
type MockIPasswordManagerMockRecorder struct {
	mock *MockIPasswordManager
}

// NewMockIPasswordManager creates a new mock instance.
func NewMockIPasswordManager(ctrl *gomock.Controller) *MockIPasswordManager {
	mock := &MockIPasswordManager{ctrl: ctrl}
	mock.recorder = &MockIPasswordManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPasswordManager) EXPECT() *MockIPasswordManagerMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockIPasswordManager) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockIPasswordManagerMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockIPasswordManager)(nil).Hash), password)
}

// Verify mocks base method.
func (m *MockIPasswordManager) Verify(passwordHash, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", passwordHash, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockIPasswordManagerMockRecorder) Verify(passwordHash, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockIPasswordManager)(nil).Verify), passwordHash, password)
}
