// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks\mock_shared.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISessionState is a mock of ISessionState interface.
type MockISessionState struct {
	ctrl     *gomock.Controller
	recorder *MockISessionStateMockRecorder
	isgomock struct{}
}

// MockISessionStateMockRecorder is the mock recorder for MockISessionState.
type MockISessionStateMockRecorder struct {
	mock *MockISessionState
}

// NewMockISessionState creates a new mock instance.
func NewMockISessionState(ctrl *gomock.Controller) *MockISessionState {
	mock := &MockISessionState{ctrl: ctrl}
	mock.recorder = &MockISessionStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionState) EXPECT() *MockISessionStateMockRecorder {
	return m.recorder
}

// ClearSession mocks base method.
func (m *MockISessionState) ClearSession() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearSession")
}

// ClearSession indicates an expected call of ClearSession.
func (mr *MockISessionStateMockRecorder) ClearSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSession", reflect.TypeOf((*MockISessionState)(nil).ClearSession))
}

// IsAuthenticated mocks base method.
func (m *MockISessionState) IsAuthenticated() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthenticated")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAuthenticated indicates an expected call of IsAuthenticated.
func (mr *MockISessionStateMockRecorder) IsAuthenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticated", reflect.TypeOf((*MockISessionState)(nil).IsAuthenticated))
}

// SessionToken mocks base method.
func (m *MockISessionState) SessionToken() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionToken")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionToken indicates an expected call of SessionToken.
func (mr *MockISessionStateMockRecorder) SessionToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionToken", reflect.TypeOf((*MockISessionState)(nil).SessionToken))
}

// SetSession mocks base method.
func (m *MockISessionState) SetSession(rawToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSession", rawToken)
}

// SetSession indicates an expected call of SetSession.
func (mr *MockISessionStateMockRecorder) SetSession(rawToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSession", reflect.TypeOf((*MockISessionState)(nil).SetSession), rawToken)
}

// MockITerminal is a mock of ITerminal interface.
type MockITerminal struct {
	ctrl     *gomock.Controller
	recorder *MockITerminalMockRecorder
	isgomock struct{}
}

// MockITerminalMockRecorder is the mock recorder for MockITerminal.
type MockITerminalMockRecorder struct {
	mock *MockITerminal
}

// NewMockITerminal creates a new mock instance.
func NewMockITerminal(ctrl *gomock.Controller) *MockITerminal {
	mock := &MockITerminal{ctrl: ctrl}
	mock.recorder = &MockITerminalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITerminal) EXPECT() *MockITerminalMockRecorder {
	return m.recorder
}

// Println mocks base method.
func (m *MockITerminal) Println(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Println", message)
}

// Println indicates an expected call of Println.
func (mr *MockITerminalMockRecorder) Println(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Println", reflect.TypeOf((*MockITerminal)(nil).Println), message)
}

// Prompt mocks base method.
func (m *MockITerminal) Prompt(label string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prompt", label)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockITerminalMockRecorder) Prompt(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockITerminal)(nil).Prompt), label)
}

// PromptSecret mocks base method.
func (m *MockITerminal) PromptSecret(label string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptSecret", label)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromptSecret indicates an expected call of PromptSecret.
func (mr *MockITerminalMockRecorder) PromptSecret(label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptSecret", reflect.TypeOf((*MockITerminal)(nil).PromptSecret), label)
}

// MockIQRRenderer is a mock of IQRRenderer interface.
type MockIQRRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockIQRRendererMockRecorder
	isgomock struct{}
}

// MockIQRRendererMockRecorder is the mock recorder for MockIQRRenderer.
type MockIQRRendererMockRecorder struct {
	mock *MockIQRRenderer
}

// NewMockIQRRenderer creates a new mock instance.
func NewMockIQRRenderer(ctrl *gomock.Controller) *MockIQRRenderer {
	mock := &MockIQRRenderer{ctrl: ctrl}
	mock.recorder = &MockIQRRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQRRenderer) EXPECT() *MockIQRRendererMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockIQRRenderer) Render(content string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Render", content)
}

// Render indicates an expected call of Render.
func (mr *MockIQRRendererMockRecorder) Render(content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockIQRRenderer)(nil).Render), content)
}
