// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination mocks\mock_totp.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "auth-cli/internal/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITOTPService is a mock of ITOTPService interface.
type MockITOTPService struct {
	ctrl     *gomock.Controller
	recorder *MockITOTPServiceMockRecorder
	isgomock struct{}
}

// MockITOTPServiceMockRecorder is the mock recorder for MockITOTPService.
type MockITOTPServiceMockRecorder struct {
	mock *MockITOTPService
}

// NewMockITOTPService creates a new mock instance.
func NewMockITOTPService(ctrl *gomock.Controller) *MockITOTPService {
	mock := &MockITOTPService{ctrl: ctrl}
	mock.recorder = &MockITOTPServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITOTPService) EXPECT() *MockITOTPServiceMockRecorder {
	return m.recorder
}

// BeginSetup mocks base method.
func (m *MockITOTPService) BeginSetup(ctx context.Context, rawSessionToken string) (*dto.TOTPSetupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginSetup", ctx, rawSessionToken)
	ret0, _ := ret[0].(*dto.TOTPSetupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginSetup indicates an expected call of BeginSetup.
func (mr *MockITOTPServiceMockRecorder) BeginSetup(ctx, rawSessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginSetup", reflect.TypeOf((*MockITOTPService)(nil).BeginSetup), ctx, rawSessionToken)
}

// CancelSetup mocks base method.
func (m *MockITOTPService) CancelSetup(rawSessionToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelSetup", rawSessionToken)
}

// CancelSetup indicates an expected call of CancelSetup.
func (mr *MockITOTPServiceMockRecorder) CancelSetup(rawSessionToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelSetup", reflect.TypeOf((*MockITOTPService)(nil).CancelSetup), rawSessionToken)
}

// ClearPendingSetups mocks base method.
func (m *MockITOTPService) ClearPendingSetups() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearPendingSetups")
}

// ClearPendingSetups indicates an expected call of ClearPendingSetups.
func (mr *MockITOTPServiceMockRecorder) ClearPendingSetups() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPendingSetups", reflect.TypeOf((*MockITOTPService)(nil).ClearPendingSetups))
}

// ConfirmSetup mocks base method.
func (m *MockITOTPService) ConfirmSetup(ctx context.Context, rawSessionToken, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmSetup", ctx, rawSessionToken, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmSetup indicates an expected call of ConfirmSetup.
func (mr *MockITOTPServiceMockRecorder) ConfirmSetup(ctx, rawSessionToken, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmSetup", reflect.TypeOf((*MockITOTPService)(nil).ConfirmSetup), ctx, rawSessionToken, code)
}

// Disable mocks base method.
func (m *MockITOTPService) Disable(ctx context.Context, rawSessionToken, password, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, rawSessionToken, password, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockITOTPServiceMockRecorder) Disable(ctx, rawSessionToken, password, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockITOTPService)(nil).Disable), ctx, rawSessionToken, password, code)
}

// ValidateEncryptedCode mocks base method.
func (m *MockITOTPService) ValidateEncryptedCode(encryptedSecret, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateEncryptedCode", encryptedSecret, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateEncryptedCode indicates an expected call of ValidateEncryptedCode.
func (mr *MockITOTPServiceMockRecorder) ValidateEncryptedCode(encryptedSecret, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateEncryptedCode", reflect.TypeOf((*MockITOTPService)(nil).ValidateEncryptedCode), encryptedSecret, code)
}

// MockISecretCipher is a mock of ISecretCipher interface.
type MockISecretCipher struct {
	ctrl     *gomock.Controller
	recorder *MockISecretCipherMockRecorder
	isgomock struct{}
}

// MockISecretCipherMockRecorder is the mock recorder for MockISecretCipher.
type MockISecretCipherMockRecorder struct {
	mock *MockISecretCipher
}

// NewMockISecretCipher creates a new mock instance.
func NewMockISecretCipher(ctrl *gomock.Controller) *MockISecretCipher {
	mock := &MockISecretCipher{ctrl: ctrl}
	mock.recorder = &MockISecretCipherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISecretCipher) EXPECT() *MockISecretCipherMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockISecretCipher) Decrypt(encoded string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", encoded)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockISecretCipherMockRecorder) Decrypt(encoded any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockISecretCipher)(nil).Decrypt), encoded)
}

// Encrypt mocks base method.
func (m *MockISecretCipher) Encrypt(plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockISecretCipherMockRecorder) Encrypt(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockISecretCipher)(nil).Encrypt), plaintext)
}
