// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mocks\mock_session.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "auth-cli/internal/domain"
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockISessionRepository is a mock of ISessionRepository interface.
type MockISessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISessionRepositoryMockRecorder
	isgomock struct{}
}

// MockISessionRepositoryMockRecorder is the mock recorder for MockISessionRepository.
type MockISessionRepositoryMockRecorder struct {
	mock *MockISessionRepository
}

// NewMockISessionRepository creates a new mock instance.
func NewMockISessionRepository(ctrl *gomock.Controller) *MockISessionRepository {
	mock := &MockISessionRepository{ctrl: ctrl}
	mock.recorder = &MockISessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionRepository) EXPECT() *MockISessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockISessionRepository) Create(ctx context.Context, value *domain.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockISessionRepositoryMockRecorder) Create(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockISessionRepository)(nil).Create), ctx, value)
}

// DeleteExpired mocks base method.
func (m *MockISessionRepository) DeleteExpired(ctx context.Context, before time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockISessionRepositoryMockRecorder) DeleteExpired(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockISessionRepository)(nil).DeleteExpired), ctx, before)
}

// FindByTokenHash mocks base method.
func (m *MockISessionRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockISessionRepositoryMockRecorder) FindByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockISessionRepository)(nil).FindByTokenHash), ctx, tokenHash)
}

// Revoke mocks base method.
func (m *MockISessionRepository) Revoke(ctx context.Context, sessionID string, revokedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, sessionID, revokedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockISessionRepositoryMockRecorder) Revoke(ctx, sessionID, revokedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockISessionRepository)(nil).Revoke), ctx, sessionID, revokedAt)
}
